# Generated by Django 2.2.13 on 2020-12-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('comment', models.CharField(max_length=400)),
                ('comment_time', models.DateField()),
            ],
        ),
    ]
